[build]
  publish = "./"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
 
  publish = "./"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
  publish = "./"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
 
  publish = "./"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
 
 